### ISSUE TITLE
Impulse may error with zeros

### ISSUE THREAD

**Issue by baggepinnen** [albheim/PoleExploration#2]
Nice package Albin :) 

I encountered the following error after having created a system with two poles and one zero. The app remains responsive, but the impulse plot fails to update and the terminal gets crazy with stack traces :P 
```
Error in callback:
ArgumentError: Impulse with a direct term from input to delay vector is not implemented. Move the delays to the output instead of input if possible.
Stacktrace:
```

**Comment by albheim** [comment]
Thanks, that should be fixed locally if I remember correctly, but will have a look.

Put it together since I wanted to check out Makie, and had heard some people at the dept complain about the app used in the AK computer labs. 
Though it seems like it won't be used this semester so I postponed the effort a bit to focus on more pressing things. 
Some other things like startup time that needs to be addressed, have played around a little with packagecompiler but it is still quite a boot time :/

**Comment by baggepinnen** [comment]
> still quite a boot time

haha yeah I noticed, but it ran very smoothly once up and running :)
